### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ZergOfSwarm** [limpbrains/somebar#3]
XFCE4, Debian 10 (Buster), Python 3.7.3
I have such an error https://ibb.co/gPKqknz 
when i run this  command 
**echo -n "black" | nc -4u -w0 localhost 1738**
What am I doing wrong?

**Comment by limpbrains** [comment]
This is example of the command you can execute from terminal.
You are trying to do this in python code, it's not possible

**Comment by ZergOfSwarm** [comment]
Thanks for answer!
In my Buster working well with that commands:
**somebar -p 1738**
and for changing a color from another terminal
**echo -n "red" | nc -u localhost 1738 &**
